# Generated by Django 3.1.5 on 2021-01-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(blank=True, max_length=10, null=True)),
                ('airport_name', models.CharField(blank=True, max_length=100, null=True)),
                ('continent', models.CharField(blank=True, max_length=3, null=True)),
                ('iso_country', models.CharField(blank=True, max_length=3, null=True)),
                ('iso_region', models.CharField(blank=True, max_length=3, null=True)),
                ('municipality', models.CharField(blank=True, max_length=40, null=True)),
                ('gps_code', models.CharField(blank=True, max_length=6, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'Airport',
                'managed': False,
            },
        ),
    ]
