# Generated by Django 3.1.5 on 2021-01-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_class', models.CharField(choices=[('E', 'Economy Class'), ('B', 'Business Class'), ('F', 'First Class')], max_length=1)),
                ('departing_date', models.DateField()),
                ('returning_date', models.DateField()),
                ('duration', models.DateTimeField()),
                ('airline', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_passengers', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], max_length=1)),
                ('child_passengers', models.CharField(choices=[('0', 0), ('1', 1), ('2', 2)], max_length=1)),
            ],
        ),
    ]
